---
# Optional override; otherwise Helm's `--namespace`,`-n` or default is used
# namespace: ""
app:
  name: "changedetection"
  image:
    repository: "lscr.io/linuxserver/changedetection.io"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 5000

# Add environment variables to deployment. Supports
# adding multiple env-vars. Comment this section if
# your app does not need environment variables.
env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "America/Los_Angeles"
  - name: BASE_URL
    value: "https://change.shakir.cloud"

ingress:
  enabled: true
  host: "change.shakir.cloud"
  ingressClassName: nginx

pvc:
  enabled: true
  name: changedetection
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  mountPath: /config
  labels:
    app: changedetection
  annotations:
    volume.kubernetes.io/description: "config mount for app: changedetection"
    custom.synology/path-hint: "maps to /volume1/k3s-main"
