---
# Optional override; otherwise Helm's `--namespace`,`-n` or default is used
# namespace: ""
app:
  name: "changedetection"
  image:
    repository: "lscr.io/linuxserver/changedetection.io"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 5000

# Add environment variables to deployment. Supports
# adding multiple env-vars. Comment this section if
# your app does not need environment variables.
env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "America/Los_Angeles"
  - name: BASE_URL
    value: "https://change.shakir.cloud"

ingress:
  enabled: true
  host: "change.shakir.cloud"
  ingressClassName: nginx

# Use the below example to mount an NFS share.
nfs:
  # Set to `true` if you want to mount an NFS share
  enabled: true
  mounts:
    # Storage server's IPv4. Replicate this item to mount multiple shares.
    - server: "10.10.50.38"
      # Share path in the storage server
      path: "/galaxy/data/changedetection"
      # Where to mount inside the pod
      mountPath: "/config"
