apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karakeep.fullname" . }}-meilisearch
  labels:
    app: {{ include "karakeep.name" . }}
    component: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "karakeep.name" . }}
      component: meilisearch
  template:
    metadata:
      labels:
        app: {{ include "karakeep.name" . }}
        component: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: "{{ .Values.meilisearch.image.repository }}:{{ .Values.meilisearch.image.tag }}"
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
            - name: MEILI_ADDR
              value: http://{{ include "karakeep.fullname" . }}-meilisearch:7700
            - name: BROWSER_WEB_URL
              value: http://{{ include "karakeep.fullname" . }}-chrome:9222
            - name: NEXTAUTH_URL
              value: http://{{ include "karakeep.fullname" . }}-web:3000
            - name: DATA_DIR
              value: {{ .Values.web.env.DATA_DIR | default "/data" | quote }}
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-web-secret
                  key: NEXTAUTH_SECRET
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-web-secret
                  key: MEILI_MASTER_KEY
          volumeMounts:
            - name: meili-data
              mountPath: /meili_data
      volumes:
        - name: meili-data
          emptyDir: {}
