# test if claim is successful:
# curl http://localhost:32400/identity
---
version: "2.1"
services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:${TAG}
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=${TIMEZONE}
      # Get a token from https://www.plex.tv/claim/ and export CLAIMTOKEN=<tokenValue>
      - PLEX_CLAIM=${CLAIMTOKEN}
      # - ADVERTISE_IP=http://${HOSTIP}:32400/
    hostname: plex.shakir.cloud
    volumes:
      - /mediaserver/config/database:/config
      - /mediaserver/config/transcode:/transcode
      - /mediaserver/data:/data
    mem_limit: 8000m
