title = "Gitleaks Config"

files = []
paths = []

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|access[_-]?key|token)[\'"\s:=]+[a-z0-9\-_.=]{10,64}'''
tags = ["key", "api", "token"]

[[rules]]
id = "k8s-secret-reference"
description = "Kubernetes secret reference in YAML (envFromSecrets, secretKeyRef, secretName)"
regex = '''(?i)(envFromSecrets|secretKeyRef|secretName)[\'"\s:]*[:\s]*[a-zA-Z0-9\-._]+'''
tags = ["k8s", "helm", "secret", "reference"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z/+]{40}['"]'''
tags = ["key", "AWS"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN( RSA)? PRIVATE KEY-----[\s\S]+?-----END( RSA)? PRIVATE KEY-----'''
tags = ["key", "private", "pem"]

[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[0-9a-zA-Z]{36,255}'''
tags = ["key", "GitHub"]

[[rules]]
id = "slack-webhook"
description = "Slack Webhook"
regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9]{8}/B[a-zA-Z0-9]{8}/[a-zA-Z0-9]{24}'''
tags = ["webhook", "slack"]

[report]
format = "sarif"
