---
namespace: ""
pvc:
  # PVC object name. should be: vol-xxxxxx
  name: ""
  # Will be used in the pvc.yaml and target deployment.yaml. should be claim-xxxxxxx
  claimName: ""
  # Default mode, can be overriden
  accessMode: ReadWriteMany
  # Ensure storage class is provisioned, otherwise PVC will stuck on "pending" status
  storageClassName: nfs-client
  # Storage size, e.g. 5Gi. It's a soft condition for non-cloud NFS providers
  storage: 5Gi
  # Use labels and annotations to track what this PVC is for and where it's mounted
  # Dynamic provisioning via the NFS CSI driver does not allow customizing the directory name
  # All mount points created in the NFS share will be named like: pvc-<unique-pvc-uid>
  labels:
    app: ""
  annotations:
    volume.kubernetes.io/description: "Shared volume for app"
    custom.synology/path-hint: "maps to /vol/k8s/path/whatever/in/you/nas"
