---
namespace: "apps"

fullnameOverride: "ci-test"
nameOverride: "ci"

app:
  image:
    repository: "dummy/app"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 2

  containerPort: 80

  service:
    port: 80
    targetPort: 80

  volumeMounts:
    - mountPath: "/app/data"
      subPath: "app"

  dbHostname: ["DB_HOST"]

  env:
    - name: DUMMY_ENV
      value: "dummy"

  envFromSecrets:
    enabled: false
    secretRefNames: []

database:
  enabled: true
  host: "dummy-db"
  port: 3306

  image:
    repository: "dummy/db"
    tag: "latest"
    pullPolicy: IfNotPresent

  volumeMounts:
    - mountPath: "/bitnami/mariadb"
      subPath: "db"

  env:
    - name: MARIADB_USER
      value: "user"

  replicas: 1

persistence:
  enabled: true
  name: "ci-pvc"
  size: "5Gi"
  accessMode: "ReadWriteMany"
  reclaimPolicy: "Retain"
  nfs:
    server: "nfs-server.example.com"
    path: "/mnt/nfs/ci"

ingress:
  enabled: true
  host: "ci.example.com"
  ingressClassName: "nginx"
  port: 80
  annotations: {}
