---
namespace: "apps"

labels:
  app: actualbudget
annotations:
  volume.kubernetes.io/description: "Shared PVC for actualbudget"
  custom.synology/path-hint: "maps to /vol1/k3s-main/actualbudget"

persistence:
  name: "actualbudget"
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "10.10.50.38"
    path: "/volume1/k3s-main/actualbudget"
