---
namespace: "apps"

labels:
  app: deemix
annotations:
  volume.kubernetes.io/description: "Shared PVC for deemix"
  custom.synology/path-hint: "maps to /vol1/k3s-main/deemix"

persistence:
  name: "deemix"
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "10.10.50.38"
    path: "/volume1/k3s-main/deemix"
