---
namespace: "apps"

labels:
  app: gaseous
annotations:
  volume.kubernetes.io/description: "Shared PVC for gaseous"
  custom.synology/path-hint: "maps to /vol1/k3s-main/gaseous"

persistence:
  name: "gaseous"
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "10.10.50.38"
    path: "/volume1/k3s-main/gaseous"
