---
namespace: "apps"

labels:
  app: jellyfin
annotations:
  volume.kubernetes.io/description: "Shared PVC for jellyfin-media"
  custom.synology/path-hint: "maps to /vol1/k3s-main/jellyfin-media"

persistence:
  name: jellyfin-media
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  nfs:
    server: "10.10.50.38"
    path: "/volume1/k3s-main/pv-jellyfin-media"
