---
namespace: "apps"
pvc:
  enabled: true
  name: pvc-metube
  claimName: claim-metube
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  labels:
    app: metube

annotations:
  volume.kubernetes.io/description: "Dynamic PVC for metube"
  custom.synology/path-hint: "maps to /vol1/k3s-main/pvc-<uid>"
