---
namespace: "apps"

labels:
  app: paperless-ngx
annotations:
  volume.kubernetes.io/description: "Shared PVC for paperless-ngx"
  custom.synology/path-hint: "maps to /vol1/k3s-main/paperless-ngx"

persistence:
  name: "paperless-ngx"
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "10.10.50.38"
    path: "/volume1/k3s-main/paperless-ngx"
