---
namespace: "apps"

labels:
  app: s-pdf
annotations:
  volume.kubernetes.io/description: "Shared PVC for s-pdf"
  custom.synology/path-hint: "maps to /vol1/k3s-main/s-pdf"

persistence:
  name: "s-pdf"
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: nfs-client
