---
namespace: "apps"
pvc:
  enabled: true
  name: pvc-s-pdf
  claimName: claim-s-pdf
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  labels:
    app: s-pdf

annotations:
  volume.kubernetes.io/description: "Dynamic PVC for s-pdf"
  custom.synology/path-hint: "maps to /vol1/k3s-main/pvc-<uid>"
