---
namespace: "apps"
pvc:
  enabled: true
  name: pvc-speedtest
  claimName: claim-speedtest
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  labels:
    app: speedtest

annotations:
  volume.kubernetes.io/description: "Dynamic PVC for speedtest"
  custom.synology/path-hint: "maps to /vol1/k3s-main/pvc-<uid>"
