---
namespace: "apps"

labels:
  app: speedtest
annotations:
  volume.kubernetes.io/description: "Shared PVC for speedtest"
  custom.synology/path-hint: "maps to /vol1/k3s-main/speedtest"

persistence:
  name: speedtest
  size: 100Mi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: nfs-client
