apiVersion: v2
name: apps
version: 0.0.1
description: A generic Helm chart for deploying stateful applications

dependencies:
  - name: nfspersistence
    version: 0.3.1
    repository: https://stackgarage.github.io/homelab/
