---
# Optional override; otherwise Helm's `--namespace`,`-n` or default is used
# namespace: ""
app:
  name: ""
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

# Add environment variables to deployment. Supports
# adding multiple env-vars. Comment this section if
# your app does not need environment variables.
env:
  - name: ENV_NAME
    value: "env_value"

ingress:
  # Set to `true` if the app needs an ingress resource.
  # Ingress Controller must be implemented first.
  enabled: false
  # Example app.example.com
  host: ""
  # Specify which ingress controller should handle the resource,
  # must match the Nginx Ingress Controller's `controller.ingressClassResource.name` field
  ingressClassName: nginx

# Stub structure. See below for NFS mount instruction.
nfs:
  mounts: []
# Use the below example to mount an NFS share.
# nfs:
#   # Set to `true` if you want to mount an NFS share
#   enabled: true
#   mounts:
#     # Storage server's IPv4. Replicate this item to mount multiple shares.
#     - server: ""
#       # Share path in the storage server
#       path: ""
#       # Where to mount inside the pod
#       mountPath: ""
