---
app:
  name: "ci-test-app"
  image:
    repository: "dummy/image"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

env:
  - name: DUMMY_ENV
    value: "dummy"

ingress:
  enabled: false
  host: "ci.example.com"
  ingressClassName: "nginx"

livenessProbe:
  enabled: false
  command: ["echo", "ok"]
  initialDelaySeconds: 20
  periodSeconds: 60
  timeoutSeconds: 10
  failureThreshold: 3

pvc:
  enabled: false
  claimName: "dummy-claim"
  mountPaths: []

affinity: {}
