apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: {{ toJson .Values.livenessProbe.command }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.pvc.enabled }}
          volumeMounts:
            {{- $claimName := .Values.pvc.claimName }}
            {{- range .Values.pvc.mountPaths }}
            - name: {{ $claimName }}
              mountPath: {{ . }}
              subPath: {{ trimPrefix "/" . }}
            {{- end }}
          {{- end }}
      {{- if .Values.pvc.enabled }}
      volumes:
        - name: {{ .Values.pvc.claimName }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claimName }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
