---
- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

# motd: Message of the Day, is a text file disaplayed upon SSH login
# typically found in Debian 11+. Safely removed here to print the
# role's custom SSH login message.
- name: Check if /etc/motd exists
  ansible.builtin.stat:
    path: /etc/motd
  register: motd_file

- name: Remove /etc/motd file (if exists)
  ansible.builtin.file:
    path: /etc/motd
    state: absent
  when: motd_file.stat.exists

- name: Add login info message
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', '{{ role_path }}/files/login') }}"
    path: "{{ default_user_home }}/.bashrc"
    marker: "## {mark} ANSIBLE MANAGED BLOCK ##"
  no_log: true

- name: Set vim as the default editor
  ansible.builtin.command: update-alternatives --set editor /usr/bin/vim.basic

- name: Backup and deploy /etc/hosts file
  ansible.builtin.template:
    src: templates/etc_hosts.j2
    dest: /etc/hosts
    backup: true
