---
# Important:
# Hostnames must match the acceptable DNS subdomain name.
# The roles/common will use the the below hostnames to set
# proper subdomain and FQDN for the host in /etc/hosts
all:
  hosts:
    k3s-main-ctrl:
      ansible_host: 10.10.50.63
    k3s-main-node-1:
      ansible_host: 10.10.50.64
    k3s-main-node-2:
      ansible_host: 10.10.50.65
    k3s-main-node-3:
      ansible_host: 10.10.50.66
    k3s-main-node-4:
      ansible_host: 10.10.50.67
    k3s-main-nuc-1:
      ansible_host: 10.10.50.53
    k3s-main-nuc-2:
      ansible_host: 10.10.50.54
    k3s-main-nuc-3:
      ansible_host: 10.10.50.55
    k3s-main-tc-1:
      ansible_host: 10.10.50.56

  children:
    k3s_main_managed_hosts:
      hosts:
        k3s-main-ctrl:
        k3s-main-node-1:
        k3s-main-node-2:
        k3s-main-node-3:
        k3s-main-node-4:
        k3s-main-nuc-1:
        k3s-main-nuc-2:
        k3s-main-nuc-3:
        k3s-main-tc-1:

    k3s_main_cluster:
      children:
        k3s_ctrl_nodes:
        k3s_worker_nodes:

    k3s_ctrl_nodes:
      hosts:
        k3s-main-ctrl:

    k3s_worker_nodes:
      hosts:
        k3s-main-node-1:
        k3s-main-node-2:
        k3s-main-node-3:
        k3s-main-node-4:
        k3s-main-nuc-1:
        k3s-main-nuc-2:
        k3s-main-nuc-3:
        k3s-main-tc-1:
