---
# Important:
# Hostnames must match the acceptable DNS subdomain name.
# The roles/common will use the the below hostnames to set
# proper subdomain and FQDN for the host in /etc/hosts
all:
  hosts:
    k3s-utils-ctrl:
      ansible_host: 10.10.50.60
    k3s-utils-node-1:
      ansible_host: 10.10.50.61
    k3s-utils-node-2:
      ansible_host: 10.10.50.62
    k3s-utils-node-3:
      ansible_host: 10.10.50.68
    k3s-main-tc-1:
      ansible_host: 10.10.50.56

  children:
    k3s_utils_managed_hosts:
      hosts:
        k3s-utils-ctrl:
        k3s-utils-node-1:
        k3s-utils-node-2:
        k3s-utils-node-3:
        k3s-main-tc-1:

    k3s_utils_cluster:
      children:
        k3s_ctrl_nodes:
        k3s_worker_nodes:

    k3s_ctrl_nodes:
      hosts:
        k3s-utils-ctrl:

    k3s_worker_nodes:
      hosts:
        k3s-utils-node-1:
        k3s-utils-node-2:
        k3s-utils-node-3:
        k3s-main-tc-1:
