name: pxmx-tf-modules-runners
namespace: actions

repository: shakir85/proxmox-tf-modules

replicas: 2

labels:
  app.kubernetes.io/managed-by: terraform
  repository/name: proxmox-tf-modules

podLabels:
  app.kubernetes.io/managed-by: terraform
  repository/name: proxmox-tf-modules
