loki:
  enabled: true
  persistence:
    enabled: true
    existingClaim: loki-local-pvc
    storageClassName: ""
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"

# Contains a geneirc job for syslog
promtail:
  enabled: true
  podLabels:
    syslog-receiver: "true"
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: syslog
          syslog:
            listen_address: 0.0.0.0:1514
            idle_timeout: 60s
            label_structured_data: yes
            labels:
              job: "syslog"
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'

# Grafana and Prometheus are deployed separately
grafana:
  enabled: false

prometheus:
  enabled: false
