---
# Whether to enable this chart. The reason of this is to allow
# stateless-apps chart that deploys releases *without* storage
# to disable this chart.
enabled: true

labels:
  app: ""
annotations:
  volume.kubernetes.io/description: "Shared volume for app"
  custom.synology/path-hint: ""

persistence:
  name: "persistence-foo"
  size: 1Gi
  accessMode: ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: ""  # e.g., 10.0.0.5
    path: ""    # e.g., /mnt/nfs/my-app
