---
# Grouping Logic:
#   managed_hosts -> all hosts that need to be managed (k8s and non-k8s hosts).
#   all_k8s       -> all k8s nodes across the board.
# ... possible updates go here ....

all:
  children:
    managed_hosts:
      children:
        k3s_main_managed_hosts:
        k3s_utils_managed_hosts:
    all_k8s:
      children:
        k3s_main_managed_hosts:
        k3s_utils_managed_hosts:

    k3s_main_managed_hosts:
      hosts:
        k3s-main-ctrl:
        k3s-main-node-1:
        k3s-main-node-2:
        k3s-main-node-3:
        k3s-main-node-4:

    k3s_utils_managed_hosts:
      hosts:
        k3s-utils-ctrl:
        k3s-utils-node-1:
        k3s-utils-node-2:
