apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: my-runnerset
  namespace: github
spec:
  replicas: 2
  template:
    spec:
      repository: my-org/my-repo
      labels:
        - self-hosted
        - linux
