---
fullnameOverride: "ci-test"
nameOverride: "ci"

app:
  image:
    repository: "dummy/app"
    tag: "latest"
    pullPolicy: IfNotPresent

  containerPort: 80

  service:
    port: 80
    targetPort: 80

  volumeMounts:
    - mountPath: "/app/data"
      subPath: "app"

  dbHostname: ["DB_HOST"]

  env:
    - name: DUMMY_ENV
      value: "dummy"

  envFromSecrets:
    enabled: false
    secretRefNames: []

  replicaCount: 1

db:
  host: "dummy-db"
  port: 3306

  image:
    repository: "dummy/db"
    tag: "latest"
    pullPolicy: IfNotPresent

  volumeMounts:
    - mountPath: "/bitnami/mariadb"
      subPath: "db"

  env:
    - name: MARIADB_USER
      value: "user"

  replicas: 1

persistence:
  existingClaim: "dummy-pvc"

ingress:
  enabled: true
  host: "ci.example.com"
  ingressClassName: "nginx"
  port: 80
  annotations: {}
