apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.name" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "paperless-ngx.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "paperless-ngx.name" . }}
    spec:
      containers:
        - name: paperless-ngx
          image: "{{ .Values.paperlessngx.image.repository }}:{{ .Values.paperlessngx.image.tag }}"
          imagePullPolicy: {{ .Values.paperlessngx.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range .Values.paperlessngx.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}

            - name: PAPERLESS_REDIS
              value: redis://{{ include "paperless-ngx.redisHost" . }}:6379

            {{- if .Values.adminSecret.enabled }}
            - name: PAPERLESS_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.usernameKey }}
            - name: PAPERLESS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.passwordKey }}
            {{- end }}
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/paperless/data
              subPath: data
            - name: shared-volume
              mountPath: /usr/src/paperless/media
              subPath: media
            - name: shared-volume
              mountPath: /usr/src/paperless/export
              subPath: export
            - name: shared-volume
              mountPath: /usr/src/paperless/consume
              subPath: consume
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.shared.existingClaim }}
