{{- if and .Values.adminSecret.enabled .Values.adminSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminSecret.name }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.adminSecret.usernameKey }}: {{ .Values.adminSecret.username | quote }}
  {{ .Values.adminSecret.passwordKey }}: {{ .Values.adminSecret.password | quote }}
{{- end }}
