apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.redisHeadlessServiceName" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379
