---
namespace: "apps"
pvc:
  enabled: true
  name: pvc-actualbudget
  claimName: claim-actualbudget
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  labels:
    app: actualbudget
  annotations:
    volume.kubernetes.io/description: "Shared PVC for actualbudget"
    custom.synology/path-hint: "maps to /vol1/k3s-main/pvc-<uid>"
