---
namespace: "apps"
pvc:
  enabled: true
  name: pvc-change-detection
  claimName: claim-change-detection
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  labels:
    app: change-detection
  annotations:
    volume.kubernetes.io/description: "Shared PVC for change-detection"
    custom.synology/path-hint: "maps to /vol1/k3s-main/pvc-<uid>"
