---
namespace: "apps"
pvc:
  enabled: true
  name: pvc-deemix
  claimName: claim-deemix
  accessMode: ReadWriteMany
  storageClassName: nfs-client
  storage: 100Mi
  labels:
    app: deemix
  annotations:
    volume.kubernetes.io/description: "Shared PVC for deemix"
    custom.synology/path-hint: "maps to /vol1/k3s-main/pvc-<uid>"
