{{- if .Values.deployRunnerDeployment }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: {{ .Values.runner_deployment_name }}
  namespace: {{ .Values.namespace }}
  labels:
{{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  replicas: {{ .Values.runnerDeployment.replicas }}
  template:
    metadata:
      labels:
{{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
{{- end }}
    spec:
      repository: {{ .Values.repository }}
      labels:
        {{- toYaml .Values.global.labels | nindent 6 }}
{{- end }}
