apiVersion: v2
name: stateful-apps
version: 0.0.1
description: A generic Helm chart for deploying stateful applications

dependencies:
  - name: nfs-persistence
    version: 0.1.0
    repository: https://shakir85.github.io/homelab/
