---
# Optional: Override the full name of the release (metadata.name).
fullnameOverride: ""

# Optional: Override just the name portion of the Helm release.
nameOverride: ""

app:
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

  # The port your application listens on inside the container.
  containerPort: 80

  service:
    # The port exposed by the K8s Service.
    port: 80
    # The targetPort that maps to containerPort.
    targetPort: 80

  volumeMounts:
    # Mount path for the Deployment.
    ## -- `mountPath`: Pointing to the app container image volume (e.g., /app/data).
    ## -- `subPath`: Pointing to the volume on the backend PVC (e.g., /mnt/nfs/someapp/data). The directory will be created automatically on the storage backend.
    - mountPath: ""
      subPath: ""

  # List of environment variable 'names' the app uses to reference the DB hostname.
  # This enables dynamic injection of the DB hostname via Helm templating.
  # Example: ["dbhost", "DATABASE_HOST"]
  dbHostname: []

  # List of additional environment variables the app needs.
  # Format:
  # - name: ENV_VAR_NAME
  #   value: somevalue
  env: []

  envFromSecrets:
    # Optional: Reference a secret to inject environment variables.
    # This assumes the secret is created separately.
    enabled: false
    secretRefNames: []

  replicaCount: 1

  # Affinity rules for app pod scheduling.
  affinity: {}


db:
  # Optional: hostname override if needed (typically injected automatically).
  host: ""
  # Port the DB pod is listening on (e.g., 3306 for MariaDB/MySQL).
  port: 3306

  image:
    # For DB images, prefer Bitnami's for NFS-friendliness.
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

  volumeMounts:
    # Mount path for the Statefulset.
    ## -- `mountPath`: Pointing to the DB container image volume (e.g., /bitnami/mariadb).
    ## -- `subPath`: Pointing to the volume on the backend PVC (e.g., /mnt/nfs/someapp/db). The directory will be created automatically on the storage backend.
    - mountPath: ""
      subPath: ""

  # DB pod's environment variables.
  # For example, use Bitnami-specific vars like MARIADB_ROOT_PASSWORD, etc.
  # Format:
  # - name: MARIADB_USER
  #   value: someuser
  env: []

  # Number of DB pod replicas
  replicas: 1

  # Affinity rules for db pod scheduling.
  affinity: {}


# If you have an existing PersistentVolumeClaim. To be shared by app + db.
# Otherwise, use `nfs-persistent-volume` to create a new PVC.
# Each container will mount their subPaths within this PVC.
existingClaim: ""

nfs-persistence:
  enabled: false

  persistence:
    name: ""
    size: ""
    accessMode: ""
    reclaimPolicy: ""
    storageClassName: ""
    nfs:
      server: ""
      path: ""

ingress:
  # Whether to enable Ingress for the app.
  enabled: true

  # Hostname for external access
  host: ""

  # IngressClass to use (e.g., "nginx", "traefik", etc.)
  ingressClassName: "nginx"

  # The port to expose via ingress (typically 80 or 443).
  port: 80

  # Extra annotations for the ingress resource.
  # Example for cert-manager:
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
  annotations: {}
