---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=${PASS}
      - SUDO_PASSWORD=${PASS}
      - PROXY_DOMAIN=${DOMAIN}
      - DEFAULT_WORKSPACE=/home/gitlab-runner/builds
    volumes:
      - /galaxy/data/vscode:/config
      - /home/gitlab-runner/builds:/home/gitlab-runner/builds
      - /home/shakir:/home/shakir
    ports:
      - 8943:8443
    restart: unless-stopped
