apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateful-app.name" . }}
  labels: {{ include "stateful-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels: {{ include "stateful-app.selectorLabels" . | nindent 6 }}-deployment
  template:
    metadata:
      labels: {{ include "stateful-app.selectorLabels" . | nindent 8 }}-deployment
    spec:
      containers:
        - name: stateful-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            {{- range .Values.app.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- $claimName := .Values.persistence.existingClaim }}
            {{- range .Values.persistence.mountPaths }}
            - name: {{ $claimName }}
              mountPath: {{ . }}
              subPath: {{ trimPrefix "/" . }}
            {{- end }}
      volumes:
        - name: {{ .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
