# Defines a headless service for the StatefulSet.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stateful-app.dbHeadlessServiceName" . }}
  labels: {{ include "stateful-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector: {{ include "stateful-app.selectorLabels" (dict "role" "db" "context" .) | nindent 4 }}-statefulset
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
