apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "stateful-app.name" . }}
  labels: {{ include "stateful-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "stateful-app.selectorLabels" (dict "role" "db" "context" .) | nindent 6 }}-statefulset
  serviceName: {{ include "stateful-app.dbHeadlessServiceName" . }}
  replicas: {{ .Values.app.replicaCount | default 1 }}
  template:
    metadata:
      labels: {{ include "stateful-app.selectorLabels" (dict "role" "db" "context" .) | nindent 8 }}-statefulset
      annotations:
    spec:
      containers:
        - name: {{ include "stateful-app.db" . }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
            {{- range .Values.db.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            {{- $claimName := .Values.existingClaim | default .Values.nfspersistence.persistence.name }}
            {{- if $claimName }}
            {{- range .Values.db.volumeMounts }}
            - name: {{ $claimName }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
      volumes:
        {{- $claimName := .Values.existingClaim | default .Values.nfspersistence.persistence.name }}
        {{- if $claimName }}
        - name: {{ $claimName }}
          persistentVolumeClaim:
            claimName: {{ $claimName }}
        {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
