apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type | default "ClusterIP" }}
  selector: {{ include "app.selectorLabels" (dict "role" "app" "context" .) | nindent 4 }}-deployment
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
