# Defines a StatefulSet for the database.
{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "app.selectorLabels" (dict "role" "database" "context" .) | nindent 6 }}-statefulset
  serviceName: {{ include "app.dbHeadlessServiceName" . }}
  replicas: {{ .Values.app.replicaCount | default 1 }}
  template:
    metadata:
      labels: {{ include "app.selectorLabels" (dict "role" "database" "context" .) | nindent 8 }}-statefulset
      annotations:
    spec:
      containers:
        - name: {{ include "app.database" . }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          {{- if .Values.database.env }}
          env:
            {{- range .Values.database.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- $claimName := .Values.existingClaim | default .Values.persistence.name }}
            {{- if $claimName }}
            {{- range .Values.database.volumeMounts }}
            - name: {{ $claimName }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
      volumes:
        {{- $claimName := .Values.existingClaim | default .Values.persistence.name }}
        {{- if $claimName }}
        - name: {{ $claimName }}
          persistentVolumeClaim:
            claimName: {{ $claimName }}
        {{- end }}
      {{- with .Values.database.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
