---
# Optional override; otherwise Helm's `--namespace`,`-n` or default is used
# namespace: ""
app:
  name: ""
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

# Add environment variables to deployment. Supports
# adding multiple env-vars. Comment this section if
# your app does not need environment variables.
env: []
# env:
#   - name: ENV_NAME
#     value: "env_value"

ingress:
  # Set to `true` if the app needs an ingress resource.
  # Ingress Controller must be implemented first.
  enabled: false
  # Example app.example.com
  host: ""
  # Specify which ingress controller should handle the resource,
  # must match the Nginx Ingress Controller's `controller.ingressClassResource.name` field
  ingressClassName: nginx

pvc:
  enabled: false
  # PVC object name
  name: ""
  accessMode: ReadWriteMany
  # Ensure storage class is provisioned, otherwise PVC will stuck on "pending" status
  storageClassName: nfs-client
  # Soft condition for non-cloud NFS providers
  storage: 1Mi
  # Mount path in the pod
  mountPath: ""
  # Use labels and annotations to track what this PVC is for and where it's mounted
  # Dynamic provisioning via the NFS CSI driver does not allow customizing the directory name
  # All mount points created in the NFS share will be named like: pvc-<unique-pvc-uid>
  labels:
    app: ""
  annotations:
    volume.kubernetes.io/description: "User-friendly description for this PVC"
    custom.synology/path-hint: "maps to /path/in/nas/volume"
