---
# Optional override; otherwise Helm's `--namespace`,`-n` or default is used
# namespace: ""
app:
  name: ""
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

# Add environment variables to deployment. Supports
# adding multiple env-vars. Comment this section if
# your app does not need environment variables.
env: []
# env:
#   - name: ENV_NAME
#     value: "env_value"

ingress:
  # Set to `true` if the app needs an ingress resource.
  # Ingress Controller must be implemented first.
  enabled: false
  # Example app.example.com
  host: ""
  # Specify which ingress controller should handle the resource,
  # must match the Nginx Ingress Controller's `controller.ingressClassResource.name` field
  ingressClassName: nginx

# This chart will not provision a PVC. If the app needs a storage, then a PVC
# must be up and running before deploying this chart.
pvc:
  enabled: false
  # List of PVC mounts the app needs
  mounts:
    # - name: unique-volume-id
    #   claimName: pvc-name-provisioned-by-storage-chart
    #   mountPath: /path/in/container
