web:
  image:
    repository: ghcr.io/karakeep-app/karakeep
    tag: release
    pullPolicy: IfNotPresent
  env:
    MEILI_ADDR: "http://meilisearch:7700"
    BROWSER_WEB_URL: "http://chrome:9222"
    DATA_DIR: "/data"

chrome:
  image:
    repository: gcr.io/zenika-hub/alpine-chrome
    tag: "124"
    pullPolicy: IfNotPresent
  command:
    - "chromium-browser"
    - "--headless"
    - "--disable-gpu"
    - "--remote-debugging-address=0.0.0.0"
    - "--remote-debugging-port=9222"
    - "--no-sandbox"

meilisearch:
  image:
    repository: getmeili/meilisearch
    tag: v1.13.3
    pullPolicy: IfNotPresent
  env:
    MEILI_NO_ANALYTICS: "true"

# Consolidated service definitions (optional if you want a single service.yaml)
services:
  - name: web
    type: ClusterIP
    ports:
      - port: 3000
        targetPort: 3000
        name: http
  - name: chrome
    type: ClusterIP
    ports:
      - port: 9222
        targetPort: 9222
        name: http
  - name: meilisearch
    type: ClusterIP
    ports:
      - port: 7700
        targetPort: 7700
        name: http
ingress:
  ingressClassName: nginx
  host: karakeep.shakir.cloud
  port: 3000
  annotations: {}
