---
- name: Copy and patch kubeconfig on Ansible controller
  hosts: server
  become: true

  tasks:
    - name: Ensure local kubeconfig dir exists
      delegate_to: localhost
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: '0700'

    - name: Load kubeconfig from control plane
      ansible.builtin.slurp:
        path: "/home/{{ ansible_user }}/.kube/config"
      register: kubeconfig_raw

    - name: Get API server endpoint from inventory (first host in 'server' group)
      ansible.builtin.set_fact:
        apiserver_endpoint: "{{ hostvars[groups['server'][0]].inventory_hostname }}"

    - name: Replace 'server' and 'default' in kubeconfig (text-based)
      delegate_to: localhost
      ansible.builtin.copy:
        dest: "/home/{{ custom_user }}/.kube/{{ env }}-config"
        content: >-
          {{
            kubeconfig_raw.content
            | b64decode
            | regex_replace('server: https?://[0-9.]+:6443',
                            'server: https://' ~ apiserver_endpoint ~ ':6443')
            | regex_replace('default', env)
          }}
        mode: '0600'
        owner: '{{ custom_user }}'

