---
# Attribution & Playbook Overview:
# -----------------
# This playbook and its associated roles are based on the k3s-ansible project,
# which can be found at: https://github.com/k3s-io/k3s-ansible
# The original project was created by `itwars` and is licensed under the Apache 2.0 license.
#
# Customization Details:
# ----------------------
# Modification to the systemd unit file located at:
# ./roles/k3s/master/templates/k3s.service.j2
#
# Modification Purpose:
# ---------------------
# - Disabled the built-in load balancer of k3s, allowing me to use MetalLB as an alternative.
# - Various modifications/additions to fit my usaecase.

- name: Play for common configurations
  hosts: dev_all_hosts
  # ignore_unreachable: true
  gather_facts: true
  become: true
  roles:
    - role: common
    - role: nfs
    - role: helm

- name: Play for configuring k3s dev cluster
  hosts: dev_all_hosts
  # ignore_unreachable: true
  gather_facts: true
  become: true
  roles:
    - role: k3s/prereq
    - role: k3s/download

- name: Configure k3s control nodes
  hosts: k3s_ctrl_nodes
  # ignore_unreachable: true
  become: true
  roles:
    - role: k3s/master
    - role: helm

- name: Configure k3s worker nodes
  hosts: k3s_worker_nodes
  # ignore_unreachable: true
  become: true
  roles:
    - role: k3s/node
