---
# Attribution & Playbook Overview:
# -----------------
# This playbook and its associated roles are based on the k3s-ansible project,
# which can be found at: https://github.com/k3s-io/k3s-ansible
# The original project was created by `itwars` and is licensed under the Apache 2.0 license.
#
# Customization Details:
# ----------------------
# In this playbook, I made a modification to the systemd unit file located at:
# ./roles/k3s/master/templates/k3s.service.j2
#
# Modification Purpose:
# ---------------------
# I disabled the built-in load balancer of k3s, allowing me to use MetalLB as an alternative.
# This change enhances flexibility in load balancing configurations.
- name: Play to reset k3s cluster
- hosts: k3s_cluster
  ignore_unreachable: true
  gather_facts: true
  become: true
  roles:
    - role: k3s/reset
