---
# Copied from: https://github.com/k3s-io/k3s-ansible/blob/main/playbooks/upgrade.yml

# Servers should be restarted sequientally to avoid etcd learner issues
# Agents have no such limitation
- name: Upgrade K3s Servers
  hosts: k3s_ctrl_nodes
  become: true
  serial: 1
  roles:
    - role: k3s_upgrade

- name: Upgrade K3s Agents
  hosts: k3s_worker_nodes
  become: true
  roles:
    - role: k3s_upgrade
