apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: node-exporter-cert
  namespace: monitoring
spec:
  secretName: node-exporter-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - node-exporter.k3s-main.example.com
