---
- name: Play for configuring server [devops]
  hosts: devops
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../roles/commons/vars/main.yml
    - ../roles/docker/vars/main.yml
    - ../roles/gitlab/vars/main.yml

  tasks:
    # Order of tasks execution matters
    - name: Install common packages
      ansible.builtin.include_tasks:
        file: ../roles/commons/tasks/main.yml
    - name: Install Docker and Docker Compose
      ansible.builtin.include_tasks:
        file: ../roles/docker/tasks/main.yml
    - name: Install and register Gitlab CI runner
      ansible.builtin.include_tasks:
        file: ../roles/gitlab/tasks/main.yml

    - name: Rebooting...
      ansible.legacy.shell: "sleep 5 && reboot"
      async: 1
      poll: 0
