---
- hosts: galaxy
  become: yes
  vars_files:
    - ../group_vars/all.yml
    - ../roles/commons/vars/main.yml
    - ../roles/docker/vars/main.yml
    - ../roles/gitlab/vars/main.yml

  vars:
    - nfs_source: "10.10.50.22:/volume1/galaxy"

  tasks:
    # Order of tasks execution matters
    - ansible.builtin.include_tasks:
        file: ../roles/commons/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: ../roles/docker/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: ../roles/gitlab/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: ../roles/gitlab/tasks/register_runner.yml
    - ansible.builtin.include_tasks:
        file: ../roles/nfs/tasks/main.yml

    - name: Rebooting...
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
