---
- name:
  hosts: harbor
  become: true
  vars_files:
    - ../group_vars/all.yml
    - ../roles/commons/vars/main.yml
    - ../roles/docker/vars/main.yml
    - ../roles/harbor/vars/main.yml

  # vars:
  #   - nfs_source: "10.10.50.22:/volume1/harbor"

  tasks:
    # Order of tasks execution matters
    - name: Install common packages
      ansible.builtin.include_tasks:
        file: ../roles/commons/tasks/main.yml
    - name: Install Docker and Docker Compose
    - name: Mount NFS volume
      ansible.builtin.include_tasks:
        file: ../roles/nfs/tasks/main.yml
    - name: Install Harbor
      ansible.builtin.include_tasks:
        file: ../roles/harbor/tasks/main.yml

    - name: Rebooting...
      ansible.legacy.shell: "sleep 5 && reboot"
      async: 1
      poll: 0
