name: Ansible K3s Plays
run-name: Ansible K3s Deployment - from ${{ github.ref_name }}
on:
  workflow_dispatch:

jobs:
  deploy-dev-cluster:
    uses: ./.github/workflows/callable-ansible-playbook.yml
    with:
      playbook: k3s.dev.playbook.yml
      inventory: inventory/k3s.dev.yml
    secrets: inherit

  deploy-staging-cluster:
    uses: ./.github/workflows/callable-ansible-playbook.yml
    with:
      playbook: k3s.staging.playbook.yml
      inventory: inventory/k3s.staging.yml
    secrets: inherit
