name: "Ansible CI Pipeline"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "ansible/**"

# Allow Reviewdog to write comments on the PR
permissions:
  pull-requests: write
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/ansible-lint.yml
    with:
      working-directory: "ansible/"
