name: Ansible K3s Plays
run-name: Ansible K3s Plays - ${{ github.event.inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - staging

jobs:
  deploy-k3s-dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/callable-k3s-ansible.yml
    with:
      inventory: inventory/dev/k3s.yml
    secrets: inherit

  deploy-k3s-staging:
    if: ${{ github.event.inputs.environment == 'staging' }}
    uses: ./.github/workflows/callable-k3s-ansible.yml
    with:
      inventory: inventory/staging/k3s.yml
    secrets: inherit
