name: Ansible Pipeline
run-name: Ansible Deployment from ${{ github.ref_name }}
on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/callable-ansible-playbook.yml
    with:
      playbook: k3s.dev.playbook.yml
      inventory: inventory/k3s.dev.yml
      environment: dev
