name: Run Ansible playbook

on:
  workflow_call:
    inputs:
      playbook:
        type: string
        required: true
        description: "Name of the Ansible playbook to run"
      inventory:
        type: string
        required: true
        description: "Path to the inventory file"
      environment:
        type: string
        required: true
        description: "Deployment environment"

jobs:
  ansible-run:
    runs-on: controller
    environment: ${{ inputs.environment }}
    steps:
      - uses: shakir85/checkout@v4

      - name: Run Ansible Playbook
        env:
          ANSIBLE_KEY_PATH: ${{ secrets.ANSIBLE_KEY_PATH }}
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
        run: |
          chmod 400 ~/.ssh/id_rsa
          cd ansible
          ansible-playbook ${{ inputs.playbook }} -i=${{ inputs.inventory }} --key-file=$ANSIBLE_KEY_PATH -u=$ANSIBLE_USER
