name: Callable K3s Ansible Workflow

on:
  workflow_call:
    inputs:
      inventory:
        type: string
        required: true
        description: "Path to the inventory file"

env:
  ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}

jobs:
  deploy-k3s:
    runs-on: controller
    steps:
      - uses: shakir85/checkout@v4

      - run: |
          cd ansible
          ansible-galaxy collection install -r requirements.yml

      - name: Deploy k3s cluster
        run: |
          cd ansible
          ansible-playbook k3s.orchestration.site -i ${{ inputs.inventory }} -u $ANSIBLE_USER

      - name: Fetch kubeconfig
        run: |
          cd ansible
          ansible-playbook fetch.kubeconfig.playbook.yml -i ${{ inputs.inventory }} -u $ANSIBLE_USER
