name: Run Ansible playbook

on:
  workflow_call:
    inputs:
      playbook:
        type: string
        required: true
        description: "Name of the Ansible playbook to run"
      inventory:
        type: string
        required: true
        description: "Path to the inventory file"

jobs:
  ansible-run:
    runs-on: controller
    steps:
      - uses: shakir85/checkout@v4
      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
        run: |
          cd ansible
          ansible-playbook ${{ inputs.playbook }} -i=${{ inputs.inventory }} -u=$ANSIBLE_USER
