name: Helmfile Deployment


on:
  workflow_call:
    inputs:
      workdirectory:
        type: string
        required: false
        default: '.'
        description: 'Helmfile working directory'
      runner-label:
        type: string
        required: false
        default: "controller"
        description: "Label of the self-hosted runner to use"

jobs:
  deploy:
    runs-on: ${{ inputs.runner-label }}
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig

    steps:
      - uses: shakir85/checkout@v4

      - name: Helmfile apply
        uses: helmfile/helmfile-action@v2.0.5
        env:
          KUBERNETES_SERVICE_HOST: ${{ env.KUBERNETES_SERVICE_HOST }}
          KUBERNETES_SERVICE_PORT: ${{ env.KUBERNETES_SERVICE_PORT }}
        with:
          helmfile-version: 'v0.150.0'
          helm-version: 'v3.11.0'
          helm-plugins: >
            https://github.com/databus23/helm-diff@v3.1.3,
          helmfile-args: apply
          helmfile-auto-init: "false"
          helmfile-workdirectory: ${{ inputs.workdirectory }}
