name: Run Ansible playbook

on:
  workflow_call:
    inputs:
      playbook:
        type: string
        required: true
        description: "Name of the Ansible playbook to run"
      inventory:
        type: string
        required: true
        description: "Path to the inventory file"
      environment:
        type: string
        required: true
        description: "Deployment environment"

jobs:
  ansible-run:
    runs-on: controller
    environment: ${{ inputs.environment }}
    steps:
      - uses: shakir85/checkout@v4

      - name: Run Ansible Playbook
        env:
          ANSIBLE_KEY: ${{ secrets.ANSIBLE_KEY_PATH }}
        run: |
          cd ansible
          ansible-playbook --key-file=$ANSIBLE_KEY ${{ inputs.playbook }} --inventory=${{ inputs.inventory }}
