name: "Pull Request Workflows"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - name: "Label PRs"
      uses: actions/labeler@v5
