name: Helmfile Apply
run-name: Helmfile Apply - ${{ github.event.inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - staging

jobs:
  helmfile-dev:
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/callable-helmfile.yml
    with:
      workdirectory: 'helmfile.d.test'
      runner-label: dev
