name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # every day at 04:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Renovate
        uses: renovatebot/github-action@v39.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
