name: Scheduled GitHub Chores

on:
  schedule:
    - cron: '0 4 * * 0' # Every Sunday at 04:00
  workflow_dispatch:

jobs:
  close-stale-issues:
    runs-on: self-hosted
    steps:
      - name: Close stale issues and PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity.'
          close-issue-message: 'This issue was closed due to inactivity.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity.'
          close-pr-message: 'This pull request was closed due to inactivity.'
          days-before-stale: 30
          days-before-close: 7

  security-scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: .gitleaks.toml
          GITLEAKS_REPORT_FORMAT: sarif
          GITLEAKS_REPORT_PATH: gitleaks-report.sarif
