name: Smoke Test

on:
  workflow_dispatch:

jobs:
  test-kubectl:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Test kubectl access
        run: |
          kubectl get namespaces
          kubectl get pods -A

      - name: Ansible ping all
        run: |
          cd ansible
          ansible all -m ping -i inventory/ --key-file=$ANSIBLE_KEY -u $ANSIBLE_USER
