name: Smoke Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  test-kubectl:
    runs-on: controller

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Test
        run: |
          cd ansible
          ansible all -u shakir --key-file $ANSIBLE_KEY -i inventory/k3s.dev.yml -m ping
