name: Terragrunt Single Stack Deployment
run-name: Deploy Terragrunt ${{ github.event.inputs.stack }} Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - prod
      stack:
        description: 'Name of the stack to deploy'
        type: choice
        options:
          - cluster
          - infra
          - platform

jobs:
  prod:
    if: ${{ github.event.inputs.environment == 'prod' }}
    uses: ./.github/workflows/callable-terragrunt-stack.yml
    secrets: inherit
    with:
      module-path: terraform/live/${{ inputs.environment }}/${{ inputs.stack }}
