name: Terragrunt Stack Deployment
run-name: Deploy Terragrunt ${{ github.event.inputs.stack }}-${{ github.event.inputs.environment }} Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - prod
      stack:
        description: 'Which stack to deploy'
        type: choice
        options:
          - cluster
          - infra
          - platform

jobs:
  stack:
    uses: ./.github/workflows/callable-terragrunt-stack.yml
    secrets: inherit
    with:
      module-path: terraform/live/${{ inputs.environment }}/${{ inputs.stack }}
