name: Terragrunt Full Environment Stack
run-name: Deploy Terragrunt ${{ github.event.inputs.environment }} Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  stack:
    uses: ./.github/workflows/callable-terragrunt.yml
    secrets: inherit
    with:
      module-path: terraform/live/${{ inputs.environment }}
