name: Terragrunt Deploy Environment Stacks
run-name: 🚀 Deploy Terragrunt ${{ github.event.inputs.environment }} Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  dev-stack:
    if: ${{ github.event.inputs.environment == 'dev' }}
    uses: ./.github/workflows/callable-terragrunt.yml
    secrets: inherit
    with:
      module-path: terraform/live/dev

  prod-stack:
    if: ${{ github.event.inputs.environment == 'prod' }}
    uses: ./.github/workflows/callable-terragrunt.yml
    secrets: inherit
    with:
      module-path: terraform/live/prod
