name: Deploy to k3s-main

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_K3S_MAIN }}" > "${GITHUB_WORKSPACE}/kubeconfig"

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'
      - name: Test RBAC with kubectl
        run: |
          export KUBECONFIG="${GITHUB_WORKSPACE}/kubeconfig"
          kubectl run nginx -n foo --image=nginx
