name: Test Runner
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: selfhosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test runners
        run: echo "Hello"
