name: Helmfile Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: ghcr.io/shakir85/cicd-tools:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_K3S_MAIN }}" > "${GITHUB_WORKSPACE}/kubeconfig"

      - name: Set up Helm plugins
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Confirm helm diff plugin
        run: helm plugin list

      - name: Run Helmfile apply
        run: helmfile apply
