name: Helmfile Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: ghcr.io/shakir85/cicd-tools:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_K3S_MAIN }}" > "${GITHUB_WORKSPACE}/kubeconfig"

      - name: Helmfile - Deploy All Releases
        run: helmfile apply
