---
# Optional override; otherwise Helm's `--namespace`,`-n` or default is used
# namespace: ""
app:
  name: "changedetection"
  image:
    repository: "lscr.io/linuxserver/changedetection.io"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    port: 80
    targetPort: 5000

  volumeMounts:
    - mountPath: /data
      subPath: change-detection

  env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: TZ
      value: "America/Los_Angeles"
    - name: BASE_URL
      value: "https://change.shakir.cloud"

ingress:
  enabled: true
  host: "change.shakir.cloud"
  ingressClassName: nginx

nfspersistence:
  enabled: true
  persistence:
    name: change-detection-pvc
    storageClassName: "nfs-client"
    accessMode: ReadWriteMany
    reclaimPolicy: Retain
    size: 200Mi
  labels:
    app: "change-detection"
  annotations:
    volume.kubernetes.io/description: "Shared volume for change-detection"
    custom.synology/path-hint: "Dynamic Provision - Check the PVC-ID"

# -- Affinity rules for pod scheduling.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k3s.shakir.cloud/size
              operator: In
              values:
                - small
