---
namespace: apps
app:
  name: "excalidraw"
  image:
    repository: "excalidraw/excalidraw"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: "ex.shakir.cloud"
  ingressClassName: nginx
