---
fullnameOverride: ""
nameOverride: "gaseous"

app:
  image:
    repository: "gaseousgames/gaseousserver"
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 80
  service:
    port: 80
    targetPort: 80
  volumeMounts:
    - mountPath: /root/.gaseous-server
      subPath: gs
  dbHostname: dbhost
  env:
    - name: TZ
      value: America/Los_Angeles
    - name: dbuser
      value: root
    - name: dbpass
      value: gaseous
  envFromSecrets:
    enabled: true
    secretRefNames:
      - gaseous-server
  replicaCount: 1

db:
  host: gsdb
  port: 3306
  image:
    repository: bitnami/mariadb
    tag: latest
    pullPolicy: IfNotPresent
  volumeMounts:
    - mountPath: /bitnami/mariadb
      subPath: gsdb
  env:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
    - name: MARIADB_ROOT_PASSWORD
      value: gaseous
    - name: MARIADB_USER
      value: gaseous
    - name: MARIADB_PASSWORD
      value: gaseous
    - name: MARIADB_DISABLE_CHOWN
      value: "yes"
  replicas: 1

persistence:
  existingClaim: gaseous

ingress:
  enabled: true
  host: games.shakir.cloud
  ingressClassName: "nginx"
  port: 80
  annotations: {}
