---
app:
  name: "it-tools"
  image:
    repository: "corentinth/it-tools"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    port: 80
    targetPort: 80

ingress:
  enabled: true
  host: "it-tools.shakir.cloud"
  ingressClassName: nginx

# -- Affinity rules for pod scheduling.
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: k3s.shakir.cloud/size
#               operator: In
#               values:
#                 - small
