---
app:
  name: "metube"
  image:
    repository: "ghcr.io/alexta69/metube"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 8081

ingress:
  enabled: true
  host: "metube.shakir.cloud"
  ingressClassName: nginx

pvc:
  enabled: true
  claimName: metube
  mountPaths:
    - /downloads
