---
namespace: apps
app:
  name: "omni-tools"
  image:
    repository: "iib0011/omni-tools"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: "omnitool.shakir.cloud"
  ingressClassName: nginx

# -- Affinity rules for pod scheduling.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: size
              operator: In
              values:
                - medium
