---
namespace: apps
app:
  name: "s-pdf"
  image:
    repository: "frooodle/s-pdf"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: "spdf.shakir.cloud"
  ingressClassName: nginx

env:
  - name: DOCKER_ENABLE_SECURITY
    value: "false"
  - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
    value: "false"
  - name: LANGS
    value: "en_US"

pvc:
  enabled: true
  claimName: claim-s-pdf
  mountPaths:
    - /customfiles
    - /configs
    - /usr/share/tessdata
