---
app:
  name: "s-pdf"
  image:
    repository: "frooodle/s-pdf"
    tag: "latest"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    port: 80
    targetPort: 8080

  volumeMounts:
    - mountPath: /customfiles
      subPath: customfiles
    - mountPath: /configs
      subPath: configs
    - mountPath: /usr/share/tessdata
      subPath: tessdata

  env:
    - name: DOCKER_ENABLE_SECURITY
      value: "true"
    - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
      value: "false"
    - name: LANGS
      value: "en_US"

ingress:
  enabled: true
  host: "spdf.shakir.cloud"
  ingressClassName: nginx

nfspersistence:
  enabled: true
  persistence:
    name: spdf-pvc
    storageClassName: "nfs-client"
    accessMode: ReadWriteMany
    reclaimPolicy: Retain
    size: 200Mi
  labels:
    app: "spdf"
  annotations:
    volume.kubernetes.io/description: "Shared volume for spdf"
    custom.synology/path-hint: "Dynamic Provision - Check the PVC-ID"

# -- Affinity rules for pod scheduling.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k3s.shakir.cloud/size
              operator: In
              values:
                - small
