---
namespace: apps
app:
  name: "speedtest"
  image:
    repository: "henrywhitaker3/speedtest-tracker"
    tag: "latest"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: "speedtest.shakir.cloud"
  ingressClassName: nginx

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: "America/Los_Angeles"
  - name: OOKLA_EULA_GDPR
    value: "true"

pvc:
  enabled: true
  claimName: speedtest
  mountPaths:
    - /config

# -- Affinity rules for pod scheduling.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k3s.shakir.cloud/size
              operator: In
              values:
                - small
